# Site settings
title: "BWeave"
email: bdrums@gmail.com
description: "Ramblings including PHP, Ruby, and JS development, DevOps, and probably the occasional mention of drums and homebrew beer."
baseurl: ""
url: "https://bweave.github.io"
title_description: "Ramblings including PHP, Ruby, and JS development, DevOps, and probably the occasional mention of drums and homebrew beer."
title_image: "https://www.gravatar.com/avatar/aff6ef12b7ae2e10498415a64d8b2a72?s=500&d=mm"
google_analytics: "UA-XXXXXXXX-XX"
disqus_account: bdrums
github_repository: https://github.com/bweave/bweave.github.io
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: brian_weaver
github_username:  bweave
# linkedin_link:
# google_plus_link:
# stackoverflow_link:

# Footer
# footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
# footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
